function Vcyl_mm3 = cylinder_volume_mm3_matlab(theta,V_c,a,l,B)
%CYLINDER_VOLUME_MM3_MATLAB
%    Vcyl_mm3 = CYLINDER_VOLUME_MM3_MATLAB(THETA,V_c,A,L,B)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Apr-2025 14:06:29

Vcyl_mm3 = V_c+(B.^2.*pi.*(a+l-a.*cos(theta)-sqrt(-a.^2.*sin(theta).^2+l.^2)))./4.0;
end
