function out1 = throttleParamEqs(in1,S_leak,D_thr,theta_rest)
%throttleParamEqs
%    OUT1 = throttleParamEqs(IN1,S_leak,D_thr,THETA_REST)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Apr-2025 14:06:46

k_0 = in1(:,1);
k_1 = in1(:,2);
k_2 = in1(:,3);
k_3 = in1(:,4);
t2 = cos(theta_rest);
t3 = D_thr.^2;
t4 = pi.^2;
t5 = pi.^3;
t6 = -S_leak;
t8 = pi./6.0e+1;
t7 = 1.0./t2;
out1 = [k_0+t6+(k_2.*t4)./3.6e+3+(k_3.*t5)./2.16e+5+k_1.*t8+(t3.*pi.*(t7.*cos(t8)-1.0))./4.0;k_0+t6+(k_1.*pi)./2.0-(t3.*pi)./4.0+(k_2.*t4)./4.0+(k_3.*t5)./8.0;k_1+(k_2.*pi)./3.0e+1+(k_3.*t4)./1.2e+3-(t3.*t7.*pi.*sin(t8))./4.0;k_1+k_2.*pi+k_3.*t4.*(3.0./4.0)];
end
