function out1 = throttleParamEqsAnalytic(S_leak,D_thr,theta_rest)
%throttleParamEqsAnalytic
%    OUT1 = throttleParamEqsAnalytic(S_leak,D_thr,THETA_REST)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Apr-2025 14:06:46

t2 = cos(theta_rest);
t3 = D_thr.^2;
t5 = pi./6.0e+1;
t4 = 1.0./t2;
t6 = cos(t5);
t7 = sin(t5);
out1 = [(t4.*(S_leak.*t2.*9.7556e+4+t2.*t3.*pi.*2.4389e+4-t3.*t6.*pi.*2.43e+4-t3.*t7.*pi.^2.*4.35e+2))./9.7556e+4,t4.*(t3.*t6.*4.5e+1-t3.*t7.*pi.*1.16e+2).*(-2.460125466398786e-3),(t4.*(t3.*t6.*5.58e+3-t3.*t7.*pi.*1.769e+3).*6.150313665996966e-4)./pi,t4.*1.0./pi.^2.*(t3.*t6.*1.2e+2-t3.*t7.*pi.*2.9e+1).*(-3.69018819959818e-2)];
end
