function out1 = volumetricEfficiencyParams(F_0,x_peak,F_peak,x_max,F_xmax)
%volumetricEfficiencyParams
%    OUT1 = volumetricEfficiencyParams(F_0,X_PEAK,F_peak,X_MAX,F_xmax)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    09-Apr-2025 14:06:48

t2 = x_max.^2;
t3 = x_max.^3;
t4 = x_peak.^2;
t5 = x_peak.^3;
t6 = 1.0./t4;
t7 = t4.*x_max;
t8 = t2.*x_peak.*2.0;
t9 = -t8;
t10 = t3+t7+t9;
t11 = 1.0./t10;
out1 = [F_0,-(t11.*(F_0.*t3.*2.0+F_0.*t5-F_peak.*t3.*2.0-F_xmax.*t5-F_0.*t2.*x_peak.*3.0+F_peak.*t2.*x_peak.*3.0))./x_peak,t6.*t11.*(F_0.*t3+F_0.*t5.*2.0-F_0.*t7.*3.0-F_peak.*t3+F_peak.*t7.*3.0-F_xmax.*t5.*2.0),-t6.*t11.*(F_0.*t2+F_0.*t4-F_peak.*t2-F_xmax.*t4-F_0.*x_max.*x_peak.*2.0+F_peak.*x_max.*x_peak.*2.0)];
end
